name: Nightly Release

on:
    schedule:
        - cron: "0 2 * * *" # Runs every day at 2 AM UTC
    workflow_dispatch: # Allows manual trigger

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Install build dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install build

            - name: Update version for nightly
              run: |
                  DATE=$(date +'%Y%m%d')
                  sed -i "s/version = .*/version = \"1.0.0.dev$DATE\"/" pyproject.toml

            - name: Build pure Python wheel
              run: python -m build --wheel --outdir dist

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
